version: "3"
services:
  nodejs:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - 4201:4201
    volumes:
      - ./:/app/server
      - /app/server/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=wforbes
      - MONGO_PASSWORD=thepassword
      - SESSION_SECRET=s1e2c3r4e5t
    command: npm run start

  mongo:
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=wforbes
      - MONGO_INITDB_ROOT_PASSWORD=thepassword
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro